import type { LucideIcon } from "lucide-react";
import {
  AlarmClock,
  Armchair,
  Baby,
  Bath,
  BatteryCharging,
  BedDouble,
  Bike,
  BookOpen,
  Bot,
  Briefcase,
  Cable,
  Camera,
  Car,
  ChefHat,
  Coffee,
  Droplets,
  Dumbbell,
  EarOff,
  Flame,
  Flower2,
  Footprints,
  Glasses,
  GlassWater,
  GraduationCap,
  Grid2x2,
  Handshake,
  HardDrive,
  Headphones,
  HeartPulse,
  House,
  Keyboard,
  Lamp,
  Laptop,
  Lock,
  MapPin,
  Mic,
  Microwave,
  Monitor,
  Moon,
  Mouse,
  MoveVertical,
  NotebookPen,
  Package,
  PersonStanding,
  Plug,
  Salad,
  ShoppingCart,
  ShowerHead,
  Shirt,
  Smile,
  Snowflake,
  Sofa,
  Speaker,
  SprayCan,
  Table,
  Trash2,
  Truck,
  UtensilsCrossed,
  Utensils,
  Wallet,
  Wand2,
  WashingMachine,
  Watch,
  Weight,
  Wind,
  Globe,
} from "lucide-react";
import type { Pick } from "@/types";

/**
 * アイテム → 線画アイコン（lucide）の割当。
 * name+tags+id へのキーワード一致（上から先勝ち）。写真の代わりに
 * 「何の物か」を一目で伝えるための視覚アンカーなので、厳密さより
 * 「外れても近縁の物」を優先した並び順にしている。
 */
const RULES: Array<[RegExp, LucideIcon]> = [
  [/目覚まし|タイマー|time timer/i, AlarmClock],
  [/イヤホン|earbuds|airpods|ノイキャン/i, Headphones],
  [/耳栓|耳せん|earplug/i, EarOff],
  [/スピーカーフォン|マイク|議事録|文字起こし|ボイス|plaud/i, Mic],
  [/スピーカー|speaker|divoom/i, Speaker],
  [/キーボード|keyboard|keychron|realforce/i, Keyboard],
  [/stream deck|tourbox|左手デバイス|ショートカット/i, Grid2x2],
  [/マウス|mouse|リストレスト|wrist/i, Mouse],
  [/モニターライト|リングライト|照明|ランプ/i, Lamp],
  [/モニター|monitor|ディスプレイ/i, Monitor],
  [/macbook|ノートpc|laptop/i, Laptop],
  // \b 必須: "Panasonic"や"nasal"の中の nas を誤検知しない
  [/\bnas\b|バックアップ/i, HardDrive],
  [/ロック|防犯|lock/i, Lock],
  [/スマートリモコン|スマートホーム|echo|nest/i, House],
  [/ドッキング|docking|kvm|ケーブル|cable/i, Cable],
  [/充電|バッテリー|電源|charging|power/i, BatteryCharging],
  [/トラッカー|紛失/i, MapPin],
  [/フットレスト|足置き/i, Footprints],
  // 椅子は「姿勢」タグを持ちがちなので姿勢より先に判定
  [/椅子|チェア|chair/i, Armchair],
  [/姿勢|骨盤/i, PersonStanding],
  [/スマートリング|ウェアラブル|apple watch|fitbit/i, Watch],
  [/グラス|メガネ|glasses/i, Glasses],
  [/電子書籍|kindle|読書|要約|audible|オーディオブック|flier/i, BookOpen],
  [/電子メモ|メモパッド|ブギー/i, NotebookPen],
  [/ウェブカメラ|webカメラ|webcam/i, Camera],
  [/ネッククーラー|クーラー|猛暑/i, Snowflake],
  // 布団系は「寝具」タグで Moon に吸われる前に判定
  [/布団|ふとん/i, BedDouble],
  [/睡眠|安眠|枕|ピロー|マットレス|寝具|ブランケット|いびき|アイマスク|sleep/i, Moon],
  [/マッサージ|筋膜|フォームローラー|ヘッドスパ|head spa|ふくらはぎ/i, HeartPulse],
  [/体重計|scale/i, Weight],
  [/歯|オーラル|舌|口臭|デンタ/i, Smile],
  [/育児|ベビー|鼻吸い|シッター|送迎|キッズ|子育て/i, Baby],
  // シャワーヘッド等が「美容」タグで Wand2 に化けないよう先に判定
  [/シャワー/i, ShowerHead],
  [/バス|珪藻土|風呂/i, Bath],
  [/脱毛|光エステ|美容/i, Wand2],
  [/ドライヤー|ヘアケア|空気|co2|花粉/i, Wind],
  [/洗濯|ハンガー/i, WashingMachine],
  [/シャツ|衣類|スチーマー|クローゼット|closet|ファッション/i, Shirt],
  [/食洗/i, Utensils],
  [/コーヒー|coffee/i, Coffee],
  [/ケトル|白湯|温活/i, Flame],
  [/圧力鍋|クック|調理鍋|自動調理/i, ChefHat],
  [/レンジ|オーブン|ゆでたまご/i, Microwave],
  [/みじん切り|計量|カッター/i, UtensilsCrossed],
  [/ゴミ/i, Trash2],
  [/掃除|クリーナー|ホコリ|モップ|拭き/i, SprayCan],
  [/加湿|乾燥対策/i, Droplets],
  [/ネットスーパー|スーパー/i, ShoppingCart],
  [/ミールキット|手料理|作り置き|食材宅配|oisix/i, Salad],
  [/ウォーター|水分/i, GlassWater],
  [/収納|整理|台車/i, Package],
  [/昇降|スタンディング/i, MoveVertical],
  [/デスク|desk/i, Table],
  [/フィットネス|運動|ジム|chocozap/i, Dumbbell],
  [/英会話|学習|語学/i, GraduationCap],
  [/\bai\b|chatgpt|perplexity/i, Bot],
  [/家計簿|お金|節約|固定費|マネー/i, Wallet],
  [/花|bloomee/i, Flower2],
  [/宅配|クリーニング|定期便/i, Truck],
  [/カーシェア|車/i, Car],
  [/luup|自転車|スクーター|移動/i, Bike],
  [/家事代行|代行|外注/i, Handshake],
  [/家具/i, Sofa],
];

/** ジャンル別フォールバック（どのルールにも当たらないとき） */
const GENRE_FALLBACK: Record<string, LucideIcon> = {
  gadget: Plug,
  housework: House,
  work: Briefcase,
  health: HeartPulse,
  service: Globe,
};

export function iconFor(pick: Pick): LucideIcon {
  const hay = `${pick.name} ${pick.tags.join(" ")} ${pick.id}`;
  for (const [re, icon] of RULES) {
    if (re.test(hay)) return icon;
  }
  return GENRE_FALLBACK[pick.genre] ?? Package;
}
